---

- name: "6.2.1 | PATCH | Ensure accounts in /etc/passwd use shadow passwords"
  block:
      - name: "6.2.1 | AUDIT | Ensure accounts in /etc/passwd use shadow passwords"
        shell: sed -e 's/^\([a-zA-Z0-9_]*\):[^:]*:/\1:x:/' -i /etc/passwd
        changed_when: false
        failed_when: false
        register: amazon2_6_2_1_shadow
        args:
            warn: false

    

    
- name: "6.2.2 | PATCH |  Ensure /etc/shadow password fields are not empty"
  command: passwd -l {{ item }}
  changed_when: false
  failed_when: false
  with_items:
      - "{{ empty_password_accounts.stdout_lines }}"
  when:
      - empty_password_accounts.rc
      - amazon2cis_rule_6_2_2
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.2
      - accounts






- name: "6.2.9 | PATCH | Ensure root is the only UID 0 account"
  command: passwd -l {{ item }}
  changed_when: false
  failed_when: false
  with_items:
      - "{{ uid_zero_accounts_except_root.stdout_lines }}"
  when:
      - uid_zero_accounts_except_root.rc
      - amazon2cis_rule_6_2_9
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.9
      - accounts
      - root
- name: "6.2.15 | PATCH | Ensure no users have .forward files"
  file:
      path: "~{{ item }}/.forward"
      state: absent
  with_items:
      - "{{ users.stdout_lines }}"
  when:
      - amazon2cis_rule_6_2_15
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.15
      - files

- name: "6.2.16 | PATCH | Ensure no users have .netrc files"
  file:
      path: "~{{ item }}/.netrc"
      state: absent
  with_items:
      - "{{ users.stdout_lines }}"
  when:
      - amazon2cis_rule_6_2_16
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.16
      - files

- name: "6.2.17 | PATCH | Ensure no users have .rhosts files"
  file:
      path: "~{{ item }}/.rhosts"
      state: absent
  with_items:
      - "{{ users.stdout_lines }}"
  when:
      - amazon2cis_rule_6_2_17
  tags:
      - level1
      - automated
      - patch
      - rule_6.2.17
      - files
